### PR TITLE
66 enable smartcar data visualization

### PR DESCRIPTION
**Pull request by arrestoteles**
- Mobile application now displays vehicle speed in km/h. Also added sensitivity to joystick throttle 💨 
- Mobile application now displays distance to other objects in meters. Also added sensitivity to joystick steering 🕹️ 
- New UI design with colors 🏳️‍🌈 
- Added our new motto "Go Park Yourself" to the mobile application screen 🚗 
 
This closes issue #66.

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by um33** [comment]
I think we need to set both speed and distance button little bit down or up because they are coming on the way of parking button. other than this everything looks good to me.

**Comment by Gabri1998** [comment]
I see the new car display is more practical and organised, great work.
According to what @um33 said , I guess that could be fixed by minimize the size of the buttons since we have one screen.

**Comment by arrestoteles** [comment]
@um33 @Gabri1998 that's the lowest I can put the speedometer and ultrasonic. Please have another look and see if it's OK 👍

**Comment by um33** [comment]
> @um33 @Gabri1998 that's the lowest I can put the speedometer and ultrasonic. Please have another look and see if it's OK 👍

i Think now they are in good place but still not sure. i think you can merge now because if there will be any conflicts then we can change the place of the buttons accordingly (if it make sense)

**Review by sh4r10 — APPROVED** [review]
Everything looks good. I have tested the changes manually to make sure that nothing breaks. The MQTT lag has also been managed, as I experienced very  little delays upon value changes. The UI is also a huge improvement over the previous implemention, providing a pleasant experience for the user. This is good work that is ready to merged into the master branch.

**Pull request merged**
