### PR TITLE
98 button to retrieve car from parking

### PR DESCRIPTION
**Pull request by sh4r10**
The parking button now switches to a retrieve button if and only if the parking algorithm has successfully completed and the car has parked itself. The button along with the joystick and other controls remains disabled under the duration of the parking/retrieval algorithms. This closes issue #98.

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by Gabri1998** [comment]
Now the retrieve button works when the the car ends parking without interfering the parking process.

**Review by Druner — CHANGES_REQUESTED** [review]
Should also disable the cruise control during parking and retrieval, otherwise it causes he car to start driving after the parking/retrieval.

**Comment by sh4r10** [comment]
> Should also disable the cruise control during parking and retrieval, otherwise it causes he car to start driving after the parking/retrieval.

Thank you for bringing this to my attention @Druner, I have fixed it now https://github.com/DIT113-V22/group-02/pull/107/commits/beb6a049ea2135c9e5ea16215a67fe64be45bbda.

**Review by Druner — APPROVED** [review]
Tested and the button works well, the rest of the buttons also successfully gets turned off during parking to not interfere with the algorithm

**Pull request merged**
