### PR TITLE
Addition of birdseye camera #64

### PR DESCRIPTION
**Pull request by Gabri1998**
Added new camera above the car to provide a birdseye  view to the user. A toggle button was added to the android applicaiton to allow the user to easily switch between the two cameras. The UI was also updated in accordance with the overall theme of the application

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by adityak714** [comment]
The Arduino tests are failing for some reason, but the SMCE is still able to compile successfully. The CI mentioned that the OV767X does not name a type during its declaration. What does that mean?

**Comment by adityak714** [comment]
> conditionally compile the camera code when on SMCE

I did that, but I somehow had to introduce a second camera. I had ``````#ifdef __SMCE__ < import OV767X.h > #endif ``````, but I think there was a preset variable called Camera, not declared explicitly in the sketch itself but still recognized by Arduino. Now, that's not the only one I wanted, and had to create a new instance of the camera called Birdseye, in our case. Maybe the *way* it is declared is wrong....?

**Review by adityak714 — COMMENTED** [review]
Ah, I see.

**Review by Druner — APPROVED** [review]
Tested and both the cameras + the camera switching button. Both works during all situations that the car can find itself in

**Pull request merged**
